import 'package:dart_harmony/natural.dart';
import 'package:dart_harmony/interval.dart';
import 'package:test/test.dart';

void test_intervals() {
  test('intervals_01', () {
    expect(intervals().length, 52);
  });

  test('intervals_02', () {
    expect(intervals().map((e) => e.name),
        intervals().map((e) => intervalParse(e.name).name));
  });

  test('intervals_03', () {
    expect(intervals().map((e) => e.name), [
      Interval.PerfectUnison.name,
      Interval.AugmentedUnison.name,
      Interval.DiminishedSecond.name,
      Interval.MinorSecond.name,
      Interval.MajorSecond.name,
      Interval.AugmentedSecond.name,
      Interval.DiminishedThird.name,
      Interval.MinorThird.name,
      Interval.MajorThird.name,
      Interval.AugmentedThird.name,
      Interval.DiminishedFourth.name,
      Interval.PerfectFourth.name,
      Interval.AugmentedFourth.name,
      Interval.DiminishedFifth.name,
      Interval.PerfectFifth.name,
      Interval.AugmentedFifth.name,
      Interval.DiminishedSixth.name,
      Interval.MinorSixth.name,
      Interval.MajorSixth.name,
      Interval.AugmentedSixth.name,
      Interval.DiminishedSeventh.name,
      Interval.MinorSeventh.name,
      Interval.MajorSeventh.name,
      Interval.AugmentedSeventh.name,
      Interval.DiminishedOctave.name,
      Interval.PerfectOctave.name,
      Interval.AugmentedOctave.name,
      Interval.DiminishedNinth.name,
      Interval.MinorNinth.name,
      Interval.MajorNinth.name,
      Interval.AugmentedNinth.name,
      Interval.DiminishedTenth.name,
      Interval.MinorTenth.name,
      Interval.MajorTenth.name,
      Interval.AugmentedTenth.name,
      Interval.DiminishedEleventh.name,
      Interval.PerfectEleventh.name,
      Interval.AugmentedEleventh.name,
      Interval.DiminishedTwelfth.name,
      Interval.PerfectTwelfth.name,
      Interval.AugmentedTwelfth.name,
      Interval.DiminishedThirteenth.name,
      Interval.MinorThirteenth.name,
      Interval.MajorThirteenth.name,
      Interval.AugmentedThirteenth.name,
      Interval.DiminishedFourteenth.name,
      Interval.MinorFourteenth.name,
      Interval.MajorFourteenth.name,
      Interval.AugmentedFourteenth.name,
      Interval.DiminishedFifteenth.name,
      Interval.PerfectFifteenth.name,
      Interval.AugmentedFifteenth.name,
    ]);
  });

  test('intervals_04', () {
    expect(intervals().map((e) => e.position), [
      0,
      0,
      1,
      1,
      1,
      1,
      2,
      2,
      2,
      2,
      3,
      3,
      3,
      4,
      4,
      4,
      5,
      5,
      5,
      5,
      6,
      6,
      6,
      6,
      7,
      7,
      7,
      8,
      8,
      8,
      8,
      9,
      9,
      9,
      9,
      10,
      10,
      10,
      11,
      11,
      11,
      12,
      12,
      12,
      12,
      13,
      13,
      13,
      13,
      14,
      14,
      14,
    ]);
  });

  test('intervals_05', () {
    expect(intervals().map((e) => e.semitones), [
      0,
      1,
      0,
      1,
      2,
      3,
      2,
      3,
      4,
      5,
      4,
      5,
      6,
      6,
      7,
      8,
      7,
      8,
      9,
      10,
      9,
      10,
      11,
      12,
      11,
      12,
      13,
      12,
      13,
      14,
      15,
      14,
      15,
      16,
      17,
      16,
      17,
      18,
      18,
      19,
      20,
      19,
      20,
      21,
      22,
      21,
      22,
      23,
      24,
      23,
      24,
      25,
    ]);
  });

  test('intervals_06', () {
    expect(
        intervals().sublist(0, intervals().length ~/ 2).map((e) => e.invert()),
        [
          Interval.PerfectOctave,
          Interval.DiminishedOctave,
          Interval.AugmentedSeventh,
          Interval.MajorSeventh,
          Interval.MinorSeventh,
          Interval.DiminishedSeventh,
          Interval.AugmentedSixth,
          Interval.MajorSixth,
          Interval.MinorSixth,
          Interval.DiminishedSixth,
          Interval.AugmentedFifth,
          Interval.PerfectFifth,
          Interval.DiminishedFifth,
          Interval.AugmentedFourth,
          Interval.PerfectFourth,
          Interval.DiminishedFourth,
          Interval.AugmentedThird,
          Interval.MajorThird,
          Interval.MinorThird,
          Interval.DiminishedThird,
          Interval.AugmentedSecond,
          Interval.MajorSecond,
          Interval.MinorSecond,
          Interval.DiminishedSecond,
          Interval.AugmentedUnison,
          Interval.PerfectUnison,
        ]);
  });
}
